### ISSUE TITLE
 ModuleNotFoundError: No module named 'segregation.spatial'

### ISSUE THREAD

**Issue by MyrnaSastre** [pysal/segregation#129] opened 2019-08-15 09:14 UTC
I'm getting this ModuleNotFoundError: 

![image](https://user-images.githubusercontent.com/30789214/63084495-2ac57680-bf00-11e9-9494-0dd72e263d58.png)

I have segregation (1.1.1) and PySAL 2.1.0 in my environment. 

Any suggestions? Thanks!

**Comment by renanxcortes** [comment] 2019-08-15 15:33
hm... weird, this is not supposed to be happening, could you share a reproducible script? Also, did you type `segregation.__version__` to check if it is indeed version 1.1.1?

**Comment by renanxcortes** [comment] 2019-08-15 15:37
Plus, to see if it is gonna work, try changing your code to:

```
import segregation
index = segregation.spatial.SpatialDissim(gdf, 'variable_name_1', 'variable_name_2')
type(index)
```

**Comment by renanxcortes** [comment] 2019-08-19 18:09
I'm closing this, since me and @myrnasastre check here locally that this was due to the usage of an older version of segregation. Newer version, like, 1.1.1, shall not present this issue.

**Closed by renanxcortes** 2019-08-19 18:09 UTC
